# Generated by Django 2.2.2 on 2019-07-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewsignup', '0002_auto_20190708_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
