# Generated by Django 2.2.2 on 2019-07-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewsignup', '0003_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=1000, null=True),
        ),
    ]
