# Generated by Django 2.2.2 on 2019-07-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crewsignup', '0004_auto_20190709_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
