# Generated by Django 2.2.2 on 2019-07-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewsignup', '0005_auto_20190709_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='in_shiraz',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='term_tabestun',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
