# Generated by Django 2.2.2 on 2019-07-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewsignup', '0006_auto_20190710_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='term_tabestun',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
