# Generated by Django 2.2.2 on 2019-07-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewsignup', '0007_auto_20190710_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='no_idea',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mashin',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
